# Generated by Django 5.2.4 on 2025-07-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_notes_alter_project_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descripción general"),
        ),
    ]
