# Generated by Django 5.2.4 on 2025-07-21 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_description'),
    ]

    operations = [
    ]
