# Generated by Django 5.2.4 on 2025-07-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_auto_20250720_2319"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="scope",
            field=models.TextField(blank=True, verbose_name="Alcance del proyecto"),
        ),
    ]
