# Generated by Django 5.2.4 on 2025-07-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Nombre de usuario opcional para perfil público o dashboard', max_length=50, null=True, unique=True),
        ),
    ]
