# Generated by Django 5.2.4 on 2025-07-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Nombre de usuario", max_length=50, unique=True
            ),
        ),
    ]
