# Generated by Django 5.2.4 on 2025-07-16 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_user_username"),
        ("customers", "0002_alter_client_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa asociada para usuarios con rol cliente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="customers.client",
            ),
        ),
    ]
