# Generated by Django 5.2.4 on 2025-07-16 19:09

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=customers.models.logo_upload_path
            ),
        ),
    ]
