# Generated by Django 5.2.4 on 2025-07-16 19:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VulnerabilityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre de la categoría",
                    ),
                ),
                (
                    "standard",
                    models.TextField(
                        blank=True,
                        help_text="Ej: OWASP Top 10 2021, OWISAM Top 10",
                        verbose_name="Marco de referencia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VulnerabilityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=50, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="vulnerabilities.vulnerabilitycategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(20)],
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "cvss_31_vector",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="CVSS 3.1 Vector",
                    ),
                ),
                (
                    "cvss_40_vector",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="CVSS 4.0 Vector",
                    ),
                ),
                (
                    "remediation",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(20)],
                        verbose_name="Remediación",
                    ),
                ),
                (
                    "remediation_complexity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        verbose_name="Complejidad de Remediación",
                    ),
                ),
                (
                    "remediation_priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                        ],
                        max_length=10,
                        verbose_name="Impacto",
                    ),
                ),
                (
                    "likelihood",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                        ],
                        max_length=10,
                        verbose_name="Probabilidad",
                    ),
                ),
                (
                    "risk_rating",
                    models.CharField(
                        editable=False, max_length=10, verbose_name="Riesgo OWASP"
                    ),
                ),
                (
                    "proof_image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen o screenshot que evidencia la vulnerabilidad.",
                        null=True,
                        upload_to="vulnerabilities/",
                        verbose_name="Captura / PoC",
                    ),
                ),
                (
                    "references",
                    models.TextField(
                        help_text="Una por línea: CWE-79, CVE-2024-12345, OWASP A01, PCI-DSS Req 6.6...",
                        verbose_name="Referencias",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vulnerabilities.vulnerabilitycategory",
                    ),
                ),
                (
                    "vuln_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vulnerabilities.vulnerabilitytype",
                    ),
                ),
            ],
        ),
    ]
