# Generated by Django 5.2.4 on 2025-07-20 00:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vulnerabilities", "0003_evidence_projectvulnerability"),
    ]

    operations = []
