# Generated by Django 5.2.4 on 2025-07-20 00:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vulnerabilities", "0004_auto_20250719_2008"),
    ]

    operations = []
